baseURL = "https://instantiator.dev"
languageCode = "en"
DefaultContentLanguage = "en"
title = "instantiator.dev"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
ignoreErrors = ["error-remote-getjson"]

# Enable Disqus
#disqusShortname = ""

# Google Analytics
# googleAnalytics = "G-SHE42ZWKEN"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# enable html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Taxonomies
[taxonomies]
  series = 'series'
  category = 'categories'
  tag = 'tags'
