  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Tools"
  weight = 300
  identifier = "tools"
  url = "/categories/tool/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

#  [[main]]
#  name = "Contact"
#  weight = 400
#  identifier = "contact"
#  url = "/contact/"